---
title: "About Me"
---

***
## My Academic and Professional Trajectory
***

After obtaining a B.S. in Mathematics and a B.A. in Economics from Brown University, and after working as a research assistant for three years in the Real Estate Finance section of the Federal Reserve Board, I earned my M.A. in Economics at the University of Rochester. I went on to work for the New York City Mayor's Office of Management and Budget for two years, where I served as a senior analyst in the Policy and Operations Research Task Force evaluating initiatives aimed at supporting people experiencing homelessness in the city. Following the onset of the COVID-19 pandemic, however, I transitioned to researching transmission dynamics in the city, which would compel me to pursue a career in public health. To that end, I am currently pursuing an M.S. in Biostatistics at the Columbia Mailman School of Public Health.

***
## My Favorite Videos
***

Equally as important as my winding path to academia is the list of YouTube videos that mean the most to me. In no particular order, here are some of the videos that never cease to bring me joy.

* [Elliot Paige comes out at the HRCF's Time to Thrive Conference in 2014.](https://www.youtube.com/watch?v=1hlCEIUATzg)

* [Nadia Hussain wins the Great British Bake Off in 2015.](https://www.youtube.com/watch?v=wNvyfsVfmu8&t=16s)

* [George the Great Dane has his best day ever.](https://www.youtube.com/watch?v=Z9vSU1Yb_7A)

As an added bonus of joy, when Elliot Paige later come as trans in 2020, the HRC YouTube channel updated the six-year-old video with his correct name and pronouns. Here's to an internet that is as dynamic as the human experience!